### ISSUE TITLE
Anyway to get changelog or release notes for salesforce-alm

### ISSUE THREAD

**Issue by maniax89** [wadewegner/sfdx-oss-plugin#12]
I saw this project was a utilizing the https://www.npmjs.com/package/salesforce-alm package and was wondering if there was any way to determine a changelog or release notes for that package dependency? I assume by building on top of the package you have had to keep track of changes to the API/CLI for salesforce and there may be a channel I am missing to be informed of the changes.

If not, feel free to close this issue - thanks!

**Comment by amphro** [comment]
These are the release notes for `salesforcedx`, which includes `salesforce-alm`. https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

However, it is not recommended building on top of `salesforce-alm` or `salesforcedx` npm packages directly. Those are meant to be consumed by the CLI and the methods may change without warning. If you want to build on top of those, you should be spawning out to the the CLI directly. Wade was just ahead of the game =)

Instead, we started to break out the core libraries used by `salesforce-alm` into the `@salesforce/core` package. This package will eventually be open sourced and follows proper semantic versioning. https://www.npmjs.com/package/@salesforce/core

Wade started to use these repos in the upgrade branch. https://github.com/wadewegner/sfdx-waw-plugin/tree/upgrade

**Comment by maniax89** [comment]
very cool - thanks for the details!

Mostly I am utilizing the same concepts found in https://github.com/leboff/sfdx-node to wrap commands in some build tasks for continuous integration and deployment automation within the node world and have been bitten a few times by the `salesforce-alm` package or its APIs changing slightly. I've been able to recover mostly and I understand that I shouldn't be doing that.

I am looking forward to the open-sourced version of the core libraries as I believe it will be extremely helpful for the day-to-day automation tasks that the `sfdx-cli` provides out of the box

**Comment by amphro** [comment]
I agree. I'm assuming you saw the doc link on the npm page, but in case you haven't you can find it here. https://developer.salesforce.com/media/salesforce-cli/docs/@salesforce/core/0.18.1/index.html

If you play around with it and have feedback, please let us know on twitter or the success community. We are still making changes and additions based on feedback from the community.
