### ISSUE TITLE
How to fix this sfdx-oss-plugin installation issue on Window

### ISSUE THREAD

**Issue by sharstream** [wadewegner/sfdx-oss-plugin#2]
Hi everyone,

How to fix this sfdx-oss-plugin installation issue to run bash scripting in sfdx pilot.
 
I am following this instruction "Using OAuth 2.0 JWT Bearer Flow" by Wade Wegner very carefully and I am getting this error.
 
Please any knows/help to outcome this installation and use in my local environment?

![sfdx-oss-plugin](https://cloud.githubusercontent.com/assets/6071127/25105347/2628b31e-2392-11e7-9b06-2f7c641c2fa0.jpg)

The problem is the plugin assumes where the other plugins are located, which appears to be different on windows. That would require a code change on the plugin side.
 
@Wade Wegner (salesforce.com) if you require salesforce-alm, then you can do `${require.resolve('salesforcedx')}/lib/scratchOrgApi` which should be more robust. Just make sure it is a loose version match so it will pick up whatever version is installed by the CLI. Otherwise it will download it's own version.

Regards,
David

**Comment by wadewegner** [comment]
This should be resolved. Please install the latest plugin or pull the latest from this repo. Thanks!
