### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by raja-M1993** [wadewegner/sfdx-oss-plugin#3]
I have an error while installing the plugin .
![plugin-error](https://cloud.githubusercontent.com/assets/26565349/25119861/7734ab62-2439-11e7-9049-91513e9203de.PNG)

I tried an another way like github.It also shown some error
![git error](https://cloud.githubusercontent.com/assets/26565349/25119890/971ce034-2439-11e7-9c60-5537eff0bd43.PNG)

Please help me to fix the errors.

**Comment by wadewegner** [comment]
I will look into fixing the plugin. But the second error is something you'll need to address. See this article: https://help.github.com/articles/error-permission-denied-publickey/

**Comment by wadewegner** [comment]
Please grab the latest plugin or pull the latest from Github. This should be fixed.
