### ISSUE TITLE
PMD code metrics in SFDX as extra plugin or PR in this repo?

### ISSUE THREAD

**Issue by rsoesemann** [wadewegner/sfdx-oss-plugin#4]
Hi Wade, I am Robert. I ported PMD to Apex last year and had a DF session about it last year. I just chatted with Reid Carlberg why not create a PMD code analysis plugin for Salesforce DX (based on your example) and present this next DF.

Creating such a plugin looks complicated and I would need a bit support. And feedback. What do you think about this?

1.  Should we integrate it as a command into this plugin? (I like this idea because the infrastructure for pulling code out of scratch orgs is not duplicated)
2. How should the plugin get PMD? A local version by the user or via maven?
3. How to get started? All this Node.js looks really intimidating.

**Comment by up2go-rsoesemann** [comment]
I know Trailhead DX is comings its way and you are a busy man with SFDX, but maybe you can provide a bit of help so I can get this started. I made you an external collaborator on my repo just for this case. ;-)

**Comment by wadewegner** [comment]
Sorry for missing this @up2go-rsoesemann! I think we should chat with  @dcarroll and figure out the best path. Will you be at TDX?

**Comment by dcarroll** [comment]
Hey Robert!

Let's chat. Our plugin model is immature at this point but I would love to work with you to start defining it.

**Comment by rsoesemann** [comment]
Hi Wade, hi Dave, glad you read this. The idea to integrate PMD into the SFDX workflow and its CLI was born a few days before last Dreamforce the night when all the tools people met. I discussed this with Nick Chen and Greg Wester.

I just revived this idea when I thought about what to submit for this years Dreamforce. My idea was again having a cospeaker but this time showing SFDX related tooling instead of CodeClimate, Codacy or Clayton.

I'm more than happy to discuss that with you via Skype in the next days (handle rsoese) or any other channel. Reid Carlberg and a PMD contributor from Appirio also showed some interest in contributing to the plugin and DF talk ;-)
You can reach me via robert.soesemann@up2go.com and @rsoesemann at Twitter.

@Wade: I won't make it to DX. Hope to make it to DF.

**Comment by wadewegner** [comment]
I'm going to go ahead and close this for now. It'd be great if you'd take a shot at this and send along a PR -- even a little bit would help me understand how to use it!

**Comment by rsoesemann** [comment]
Sure and sorry for not being active here. To much work and still not sure if it really is worth it to add PMD to a DX CLI when the developer could just use PMD in local Command line. I doubt it.

**Comment by dcarroll** [comment]
I think there is an interesting use case for a feature that does not yet exist for plugin developers. The feature is post/pre command execution hooks that can abort the command or allow it to complete.  In this case, I would pre-hook the push command, run the PMD, and if all is well, allow it to complete, if not abort it with proper messaging.

As to whether it would make a good standalone plugin, that is a good question and really depends on the ability to easily script it out in a CI/CD situation as is.
